stages:
  - install
  - test
  - build

variables:
  NODE_VERSION: "18"

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:${NODE_VERSION}
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  image: node:${NODE_VERSION}
  dependencies:
    - install
  script:
    - npm run typecheck || echo "No typecheck configured"
    - npm test || echo "No tests configured"
  only:
    - merge_requests
    - main
    - develop

build:
  stage: build
  image: node:${NODE_VERSION}
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main
    - develop
