stages:
  - install
  - test
  - build

variables:
  NODE_VERSION: "20"

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

install:
  stage: install
  image: node:20
  script:
    - echo "📦 Installing root, frontend, and backend dependencies"
    - npm install
    - cd frontend && rm -rf node_modules package-lock.json && npm install
    - cd ../backend && rm -rf node_modules package-lock.json && npm install
  artifacts:
    paths:
      - frontend/node_modules/
      - backend/node_modules/
    expire_in: 3 hrs

test:
  stage: test
  image: node:20
  dependencies:
    - install
  script:
    - echo "🧪 Running frontend and backend typecheck/tests"
    - cd frontend
    - npm run typecheck || echo "No frontend typecheck configured"
    - npm test || echo "No frontend tests configured"
    - cd ../backend
    - npm run typecheck || echo "No backend typecheck configured"
    - npm test || echo "No backend tests configured"

build:
  stage: build
  image: node:20
  dependencies:
    - install
  script:
    - echo "🏗️ Building both frontend and backend using root script"
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
      - backend/build/
    expire_in: 2 weeks