stages:
  - install
  - test
  - build

variables:
  NODE_VERSION: "18"

cache:
  paths:
    - node_modules/

before_script:
  - echo "Running CI on branch: $CI_COMMIT_BRANCH"

install:
  stage: install
  image: node:${NODE_VERSION}
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 3 hour

test:
  stage: test
  image: node:${NODE_VERSION}
  dependencies:
    - install
  script:
    - npm run typecheck || echo "No typecheck configured"
    - npm test || echo "No tests configured"

build:
  stage: build
  image: node:${NODE_VERSION}
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 2 week
